### ISSUE TITLE
Raid Read Error

### ISSUE THREAD

**Issue by Titonka** [LegoFigure11/RaidCrawler#164]
![IMG_0244](https://github.com/LegoFigure11/RaidCrawler/assets/145739666/650a51f0-5d1e-49a2-92ad-80fde848df10)
![IMG_0214](https://github.com/LegoFigure11/RaidCrawler/assets/145739666/6af1920c-58b8-406f-b0e4-f48eb521b308)

This error occurs often and seemingly randomly including sometimes upon immediately pressing connect or advance date in Raidcrawler.

**Comment by LegoFigure11** [comment]
Could you please provide a dump of the save or the raid block when this error occurs? I've been running it for about 7 hours now and am thus far unable to replicate the problem.

**Comment by Banzail** [comment]
This seem to bite eachother with new event that got released recently. Got same problem

**Comment by LegoFigure11** [comment]
At least 6 of those hours have been on the new event, so I don't think that's it. Could you please provide a save file or a dump of the raid block?

**Comment by supersaiyajingoku** [comment]
Not OP but the same thing happens to me but only on my scarlet save file. Never got the error on violet.
Raid Block:
01 00 00 00 13 00 00 00 01 00 00 00 06 00 00 00 54 53 3E C2 00 00 00 00 02 00 00 00 00 00 00 00

**Comment by Banzail** [comment]
Ah yes. Its in scarlet related with 6* (black) raids in dlc. Causing this error

**Comment by alemany89** [comment]
I was able to reproduce the same kind of issue on Scarlet, not for a black chrystal but with the events ones, heres the log file -> 
[raid_dbg_BaseROM.txt](https://github.com/LegoFigure11/RaidCrawler/files/12698357/raid_dbg_BaseROM.txt)

**Comment by alemany89** [comment]
I found that having the RC filter with Duskull was reproducing the issue on my side, Legofigure, i've sent you the save via discord. 

On my side the fix was just removing the filter with Duskull.

**Comment by alemany89** [comment]
Im testing how to skip the issue and i've found something. I've disabled the following checkbox for kitakami
![image](https://github.com/LegoFigure11/RaidCrawler/assets/46443105/8e0eccb5-450f-4d59-bb70-d3c3597c0969)
 and the issue is not reproduced anymore, it seems like a performance issue when trying to scan both regions

**Comment by Titonka** [comment]
Hello, I am the original poster. To be honest, I am new to CFW so I am not entirely sure how to upload my save file or raid block. I saved as soon as I got the error and saved my file in JKSV but I can't find the file to upload it :( For now, I have tried to attach the log of the message I am getting. In case this information is useful, I am also using Pokemon Scarlet, but I am still receiving the error when scanning only Kitakami. I was having this issue before the events as well. Thank you very much for looking into the problem and sorry I haven't been super helpful. On Sep 22, 2023, at 1:01 PM, alemany89 ***@***.***> wrote:Im testing how to skip the issue and i've found something. I've disabled the following checkbox for kitakami  and the issue is not reproduced anymore, it seems like a performance issue when trying to scan both regions—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
No encounters found.
Den: 1
Progress: 4
Difficulty: 95
Group ID: -1
isFixed: False
isBlack: True
isEvent: False

**Comment by alemany89** [comment]
There are 2 types of issue here @Titonka, one is yours that is regarding a black crystal in dlc region, mine is related for the new event pokemons in the vanilla region:

so in summary there are two error files:
your issue regarding black crystal in kitakami region -> 
[raid_dbg_KitakamiROM.txt](https://github.com/LegoFigure11/RaidCrawler/files/12703737/raid_dbg_KitakamiROM.txt)

The issue in the vanilla region regarding the new event pokemon ->
[raid_dbg_BaseROM.txt](https://github.com/LegoFigure11/RaidCrawler/files/12703756/raid_dbg_BaseROM.txt)


The second one can be skipped by disabling the scanning into the dlc section, for the first one i dont have any clue yet



Notes: Regarding how to export the save file you can find on google tutorials using google and searching for JKSV anyway if you have questions regarding CFW you can go to https://discord.gg/nintendohomebrew in order to know more about it

**Comment by CardBreaker** [comment]
I think I found the issue with Kitakami black crystals. It's a typo in GetRateTotalKitakamiSL. The value for 6 star raids should be 2**4**75, not 2575.
