### ISSUE TITLE
v1.1.0

### ISSUE THREAD

**Issue by jnovack** [LegoFigure11/RaidCrawler#79]
Time for a v1.0.10 tag, so that the release version doesn't show a white screen? :)

**Comment by architdate** [comment]
Yeah, that's the plan tomorrow I suppose. I just wanted to get #70 and #71 are handled before we do the release. If the conflicts arnt fixed, ill just implement the same logic myself and push

**Comment by architdate** [comment]
Also it will most likely be 1.1.0 next :)

**Comment by LegoFigure11** [comment]
I also wanna refactor settings to save to JSON before 1.1.0, I'll try to do that today

**Comment by architdate** [comment]
TODO before v1.1.0 release:
- [ ] JSON based settings instead of application settings (for persistence across assembly versions)
- [ ] #66 (@ViolentSpatula 's proposed webhook will likely be the best solution here)
- [ ] Search bar update with search timing on streamer view (which can be PR'd by @jnovack )

I think we should be good to go to release after these are sorted out. Should be quite a milestone release too since it won't require frequent updates after that point onwards!

Thank you to all the contributors for their help with these in advance <3

**Comment by jnovack** [comment]
> Should be quite a milestone release too

Should be good for a while before they release v1.2 and break everything. :)

**Comment by jnovack** [comment]
Let's break out any individual tasks as issues and get them assigned.  We can make a milestone for everything included.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/387006/212648486-2cc9e258-50e1-4965-9ebf-bfaf5591043a.png">

Although, some MASSIVE changes have already been released, we don't have to wait on something to bump the version just to get a proper release out there.   Having a 4-week old stale release and relying on people to download nightlies is not a good experience.  Bump and go, numbers don't mean anything.

**Comment by architdate** [comment]
One thing I need to ensure for sure before I make a release is Settings as a json
The reason for this is I dont want assembly updates disrupting settings users have had. Once that is taken care of, I'll make a release.
